### ISSUE TITLE
语法错误

### ISSUE THREAD

**Issue by hi-noikiy** [phonegapX/QuantBot#1]
Rc8"response"3{s7"success"s7"message"s4"data"}o0{fs27"near "OFFSET": syntax error"n}z
还有不管是不是科学上网，都出现下面的情况
![image](https://user-images.githubusercontent.com/32630320/40264944-02e757ea-5b61-11e8-912a-9a0035946d92.png)

**Comment by phonegapX** [comment]
你这应该还是与科学上网有关，代码里面可以指定代理。

**Comment by hi-noikiy** [comment]
你好。我用了全局代理都不行。还有代码里面指定代理是在哪个地方？

**Comment by hi-noikiy** [comment]
代码里指定了代理还是不行

**Comment by hi-noikiy** [comment]
这里是不是只有OKEX的现货，没有期货

**Comment by phonegapX** [comment]
你代理是不是没设置对，代码里面有设置代理地址的地方，你仔细看代码。
OKEX有期货啊，交易所选项里面有选择OKEX期货。

**Comment by hi-noikiy** [comment]
找到了期货。但是api/okex.future.go里面没有代理的配置。我按照okex.go的方法配置了一个。deploy之后点击run it 还是一闪而过，状态还是halt。请问有微信交流群吗？

**Comment by hi-noikiy** [comment]
![image](https://user-images.githubusercontent.com/32630320/40667418-b29035a0-6394-11e8-887e-1e8c8609b1ff.png)

**Comment by hi-noikiy** [comment]
测试了okex跟okex.future
okex.future总是提示Please add at least one exchange

**Comment by phonegapX** [comment]
这个问题我偶尔也碰到，会修改

**Comment by phonegapX** [comment]
是可以建立一个微信交流群
