### ISSUE TITLE
Python接口

### ISSUE THREAD

**Issue by kaixinbuyu** [phonegapX/QuantBot#3]
不清楚原项目为什么用javascript作为策略开发语言，为什么不用python。pandas，numpy这些数据分析包才能利用起来。

**Comment by phonegapX** [comment]
可能是用户基数吧，近些年web前端和nodejs的发展让javascript用户量大增。而且现在在数字货币量化领域的开源项目都是用javascript开发的，比如gekko，tribeca，zenbot等。不过传统市场量化开源项目主流还是python，不过它们也在向数字货币领域迈进，比如zipline，rqalpha，vnpy等。不过javascript+web界面确实符合当前的主流思想，像vnpy之前还一直是qt类型的界面，不过最近也推出了web界面。最后说个题外话，我觉得原项目和botvs好像啊，搞不好原作者后来闭源开发botvs项目去了，botvs是支持python的。

**Comment by kaixinbuyu** [comment]
感谢推荐botvs 我也去看看botvs。
